### ISSUE TITLE
Error during "gulp build"

### ISSUE THREAD

**Issue by dstsay** [fouad/famous-angular-cordova-seed#2]
Hi, I'm getting this error when running gulp build - not sure why

[09:11:43] Using gulpfile ~/Projects/famous-angular-cordova-seed-master/gulpfile.js
[09:11:43] Starting 'build'...
[09:11:43] Starting 'templates'...
[09:11:43] Starting 'sass'...
[09:11:43] Starting 'images'...
[09:11:43] Starting 'libScripts'...
[09:11:43] Starting 'libAssets:ionicIcons'...
[09:11:43] Starting 'libAssets:fonts'...
[09:11:43] Starting 'libAssets:require'...
[09:11:43] Finished 'build' after 312 ms
[09:11:43] Finished 'images' after 24 ms
[09:11:43] gulp-size: 'libScripts' total 0 B
[09:11:43] Finished 'libScripts' after 27 ms
[09:11:43] Finished 'libAssets:ionicIcons' after 18 ms
[09:11:43] Finished 'libAssets:require' after 15 ms

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: source string:25: error: file to import not found or unreadable: "app/lib/ionic/scss/ionicons/ionicons.scss"

**Comment by fouad** [comment]
@dstsay did bower install run correctly? If not, try `bower install`. If it's not installed, `npm install -g bower`

**Comment by dstsay** [comment]
ok thanks, i reran bower install, then nom install and now it works.

So to change the code, I change it in the ./app directory?

On Fri, Dec 5, 2014 at 3:55 PM, Fouad Matin notifications@github.com
wrote:

> @dstsay https://github.com/dstsay did bower install run correctly? If
> not, try bower install. If it's not installed, npm install -g bower
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fouad/famous-angular-cordova-seed/issues/2#issuecomment-65852977
> .

## 

..............................................................
David Tsay, M.D., Ph.D.
Department of Cardiology
Columbia University Medical Center - New York Presbyterian Hospital

www.linkedin.com/in/davidtsay

P: (347) 229-1467
F: (815) 318-1930
..............................................................

**Comment by fouad** [comment]
Good to hear and yep!

**Comment by dstsay** [comment]
This is an unrelated question but do you know if famous's demo code is
available ?

On Friday, December 5, 2014, Fouad Matin notifications@github.com wrote:

> Good to hear and yep!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fouad/famous-angular-cordova-seed/issues/2#issuecomment-65883291
> .

## 

..............................................................
David Tsay, M.D., Ph.D.
Department of Cardiology
Columbia University Medical Center - New York Presbyterian Hospital

www.linkedin.com/in/davidtsay

P: (347) 229-1467
F: (815) 318-1930
..............................................................

**Comment by fouad** [comment]
Their current demos are not open yet. They're rewriting them so maybe it'll be open when it's released.

**Comment by dstsay** [comment]
Good to know - thanks! I can stop searching for them now. . .

On Sat, Dec 6, 2014 at 8:47 PM, Fouad Matin notifications@github.com
wrote:

> Their current demos are not open yet. They're rewriting them so maybe
> it'll be open when it's released.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fouad/famous-angular-cordova-seed/issues/2#issuecomment-65922909
> .

## 

..............................................................
David Tsay, M.D., Ph.D.
Department of Cardiology
Columbia University Medical Center - New York Presbyterian Hospital

www.linkedin.com/in/davidtsay

P: (347) 229-1467
F: (815) 318-1930
..............................................................
